{
    "openapi": "3.0.2",
    "info": {
        "title": "Office Booking Service RESTful API",
        "version": "1.0.0",
        "description": "OpenAPI for Office Booking Service RESTful API",
        "license": {
            "name": "APACHE 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        }
    },
    "servers": [
        {
            "description": "Office Booking Service Restful API Server",
            "url": "https://{environment}.localhost.com/api/v1",
            "variables": {
                "environment": {
                    "description": "Server Environment",
                    "default": "development",
                    "enum": [
                        "development",
                        "staging",
                        "production"
                    ]
                }
            }
        }
    ],
    "paths": {
        "/register": {
            "post": {
                "tags": ["User"],
                "summary": "Create new user",
                "description": "Create new user",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json":{
                            "schema":{
                                "type": "object",
                                "properties": {
                                    "full_name":{
                                        "type": "string",
                                        "minLength": 1,
                                        "required": true
                                    },
                                    "gender":{
                                        "type": "string",
                                        "minLength": 1,
                                        "required": true
                                    },
                                    "email":{
                                        "type": "string",
                                        "minLength": 3,
                                        "required": true
                                    },
                                    "password":{
                                        "type": "string",
                                        "minLength": 8,
                                        "required": true
                                    },
                                    "confirmation_password":{
                                        "type": "string",
                                        "minLength": 8,
                                        "required": true
                                    }
                                }
                            },
                            "examples": {
                                "Kobe":{
                                    "description": "Example create new user Kobe",
                                    "value":{
                                        "full_name": "Kobe Bryant",
                                        "gender": "Male",
                                        "email": "kobebryant@gmail.com",
                                        "password": "kobebryant123",
                                        "confirmation_password": "kobebryant123"
                                    }
                                },
                                "Oprah":{
                                    "description": "Example create new user Oprah",
                                    "value":{
                                        "full_name": "Oprah Winfrey",
                                        "gender": "Female",
                                        "email": "oprah@gmail.com",
                                        "password": "oprah123",
                                        "confirmation_password": "oprah123"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created - success create new user",
                        "content": {
                            "application/json":{
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "id":{
                                            "type": "number",
                                            "format": "int64"
                                        },
                                        "created_at":{
                                            "type": "string",
                                            "format": "date-time"
                                        },
                                        "updated_at":{
                                            "type": "string",
                                            "format": "date-time"
                                        },
                                        "deleted_at":{
                                            "type": "string",
                                            "format": "date-time",
                                            "nullable": true
                                        },
                                        "full_name":{
                                            "type": "string"
                                        },
                                        "gender":{
                                            "type": "string"
                                        },
                                        "email":{
                                            "type": "string",
                                            "format": "email"
                                        },
                                        "password":{
                                            "type": "string",
                                            "format": "password"
                                        }
                                    }
                                },
                                "examples": {
                                    "Kobe":{
                                        "description": "Example success create new user Kobe",
                                        "value":{
                                            "id": 1,
                                            "created_at": "1970-01-01T21:27:11.764+07:01",
                                            "updated_at": "1970-01-01T21:27:11.764+07:01",
                                            "deleted_at": null,
                                            "full_name": "Kobe Bryant",
                                            "gender": "Male",
                                            "email": "kobebryant@gmail.com",
                                            "password": "kobebryant123"
                                        }
                                    },
                                    "Oprah":{
                                        "description": "Example success create new user Oprah",
                                        "value":{
                                            "id": 2,
                                            "created_at": "1970-01-01T23:30:11.764+07:01",
                                            "updated_at": "1970-01-01T23:30:11.764+07:01",
                                            "deleted_at": null,
                                            "full_name": "Oprah Winfrey",
                                            "gender": "Female",
                                            "email": "oprah@gmail.com",
                                            "password": "oprah123"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "tags": ["User"],
                "summary": "User login",
                "description": "User login to get token for authentication",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json":{
                            "schema":{
                                "type": "object",
                                "properties": {
                                    "email":{
                                        "type": "string",
                                        "minLength": 3,
                                        "required": true
                                    },
                                    "password":{
                                        "type": "string",
                                        "minLength": 8,
                                        "required": true
                                    }
                                }
                            },
                            "examples": {
                                "Kobe":{
                                    "description": "Example login user Kobe",
                                    "value":{
                                        "email": "kobebryant@gmail.com",
                                        "password": "kobebryant123"
                                    }
                                },
                                "Oprah":{
                                    "description": "Example login user Oprah",
                                    "value":{
                                        "email": "oprah@gmail.com",
                                        "password": "oprah123"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK - success Login",
                        "content": {
                            "application/json":{
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "token":{
                                            "type": "string",
                                            "format": "jwt-token"
                                        }
                                    }
                                },
                                "examples": {
                                    "Kobe":{
                                        "description": "Example success login user Kobe",
                                        "value":{
                                            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZXhwIjoxNjY3NzQ4NDc5fQ.9dIFTxABmUEZpQtZLpocS5FRzHnreuuXckBYACkRBBQ"
                                        }
                                    },
                                    "Oprah":{
                                        "description": "Example success login user Oprah",
                                        "value":{
                                            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZXhwIjoxNjY4ODA1NjcwfQ.L5QD2kPuGjrGO7K7VRNXdqsNWb4aZWCQa9EBHDIJBC8"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/admin": {
            "get": {
                "security": [
                    {
                        "adminBearerAuth": []
                    }
                ],
                "tags": ["Admin"],
                "summary": "Get admins",
                "description": "get list of admins",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Admins"
                                },
                                "examples": {
                                    "success": {
                                        "description": "Example success get all admins",
                                        "value": [
                                            {
                                                "username": "admin1",
                                                "password": "admin1"
                                            },
                                            {
                                                "username": "admin2",
                                                "password": "admin2"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "adminBearerAuth": []
                    }
                ],
                "tags": ["Admin"],
                "summary": "Create admin",
                "description": "create new admin account",
                "parameters": [],
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Admins"
                                },
                                "examples": {
                                    "success": {
                                        "description": "Example success create admin",
                                        "value": {
                                            "username": "admin1",
                                            "password": "admin1"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/admin/{adminId}": {
            "get": {
                "security": [
                    {
                        "adminBearerAuth": []
                    }
                ],
                "tags": ["Admin"],
                "summary": "Get admin",
                "description": "Get admin account by id",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/AdminId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Admins"
                                },
                                "examples": {
                                    "success": {
                                        "description": "Example success get admin",
                                        "value": {
                                            "username": "admin1",
                                            "password": "admin1"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "adminBearerAuth": []
                    }
                ],
                "tags": ["Admin"],
                "summary": "Update admin",
                "description": "Update admin username",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/AdminId"
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json":{
                            "schema":{
                                "$ref": "#/components/schemas/Admins"
                            },
                            "examples": {
                                "Success":{
                                    "description": "Example update",
                                    "value":{
                                        "username": "kobebryant",
                                        "password": "kobebryant123"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Admins"
                                },
                                "examples": {
                                    "success": {
                                        "description": "Example success get all admins",
                                        "value": {
                                            "username": "admin1",
                                            "password": "admin1"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "adminBearerAuth": []
                    }
                ],
                "tags": ["Admin"],
                "summary": "Delete admin",
                "description": "Delete admin account",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/AdminId"
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json":{
                            "schema":{
                                "$ref": "#/components/schemas/Admins"
                            },
                            "examples": {
                                "Success":{
                                    "description": "Example update",
                                    "value":{
                                        "username": "kobebryant",
                                        "password": "kobebryant123"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Admins"
                                },
                                "examples": {
                                    "success": {
                                        "description": "Example success get admin",
                                        "value": {
                                            "status": "success",
                                            "message": "admin deleted",
                                            "data": ""
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Admins"
                                },
                                "examples": {
                                    "failed": {
                                        "description": "Example failed get admin",
                                        "value": {
                                            "status": "failed",
                                            "message": "admin not found",
                                            "data": ""
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/office": {
            "get": {
                "tags": ["Office"],
                "summary": "Get all office",
                "description": "Get all active office by location",
                "parameters": [
                    {
                      "name": "name",
                      "in": "query",
                      "required": false,
                      "description": "Filter office by location",
                      "schema": {
                        "type": "string",
                        "nullable": true,
                        "minLength": 1,
                        "maxLength": 100
                      },
                      "examples": {
                        "Jakarta Utara": {
                          "description": "Working space at Jakarta Utara",
                          "value": "Jakarta Utara"
                        },
                        "Jakarta Pusat": {
                          "description": "Working space at Jakarta Pusat",
                          "value": "Jakarta Pusat"
                        }
                      }
                    }
                  ],
                  "responses": {
                    "200": {
                        "description" : "Success get all office",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type" : "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "description": {
                                            "type": "string"
                                        },
                                        "tags": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "success": {
                                        "description": "Example success get all office",
                                        "value": [
                                            {
                                                "id": "1",
                                                "name": "Noble House",
                                                "description": "Working space based in Jakarta Utara",
                                                "tags":[
                                                    "Jakarta Utara"
                                                ]
                                            },
                                            {
                                                "id": "2",
                                                "name": "Sinarmas Tower",
                                                "description": "Working space based in Jakarta Pusat",
                                                "tags":[
                                                    "Jakarta Pusat"
                                                ]
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                  }
            },
            "post": {
                "tags": ["Office"],
                "summary": "Create new office",
                "description": "Create new office to database",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type" : "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "description": {
                                            "type": "string"
                                        },
                                        "tags": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                            },
                            "examples": {
                                "Jakarta Utara": {
                                    "description": "Example create office at Jakarta Utara",
                                    "value": {
                                        "name": "UnionSpace",
                                        "description": "Working space based in Jakarta Utara",
                                        "tags": [
                                            "Jakarta Utara"
                                        ]
                                    }
                                },
                                "Jakarta Pusat": {
                                    "description": "Example create office at Jakarta Pusat",
                                    "value": {
                                        "name": "Kedasi",
                                        "description": "Working space based in Jakarta Pusat",
                                        "tags": [
                                            "Jakarta Pusat"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success create office",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type" : "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "description": {
                                            "type": "string"
                                        },
                                        "tags": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Jakarta Utara": {
                                        "description": "Success create office at Jakarta Utara",
                                        "value": {
                                            "name": "UnionSpace",
                                            "description": "Working space based in Jakarta Utara",
                                            "tags": [
                                                "Jakarta Utara"
                                            ]
                                        }
                                    },
                                    "Jakarta Pusat": {
                                        "description": "Example create office at Jakarta Pusat",
                                        "value": {
                                            "name": "Kedasi",
                                            "description": "Working space based in Jakarta Pusat",
                                            "tags": [
                                            "Jakarta Pusat"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/office/{officeId}": {
            "put": {
                "tags": ["Office"],
                "summary": "Update existing office",
                "description": "Update existing office in database",
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "required": true,
                        "description": "Office id for updated",
                        "schema": {
                          "type": "string",
                          "nullable": true,
                          "minLength": 1,
                          "maxLength": 100
                        },
                        "examples": {
                          "Jakarta Utara": {
                            "description": "Working space at Jakarta Utara",
                            "value": "Jakarta Utara"
                          },
                          "Jakarta Pusat": {
                            "description": "Working space at Jakarta Pusat",
                            "value": "Jakarta Pusat"
                          }
                        }
                      }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type" : "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "description": {
                                            "type": "string"
                                        },
                                        "tags": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                            },
                            "examples": {
                                "Jakarta Utara": {
                                    "description": "Example office at Jakarta Utara",
                                    "value": {
                                        "name": "UnionSpace",
                                        "description": "Working space based in Jakarta Utara",
                                        "tags": [
                                            "Jakarta Utara"
                                        ]
                                    }
                                },
                                "Jakarta Pusat": {
                                    "description": "Example office at Jakarta Pusat",
                                    "value": {
                                        "name": "Kedasi",
                                        "description": "Working space based in Jakarta Pusat",
                                        "tags": [
                                            "Jakarta Pusat"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success update office",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type" : "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "description": {
                                            "type": "string"
                                        },
                                        "tags": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Jakarta Utara": {
                                        "description": "Example updated office at Jakarta Utara",
                                        "value": {
                                            "name": "UnionSpace",
                                            "description": "Working space based in Jakarta Utara",
                                            "tags": [
                                                "Jakarta Utara"
                                            ]
                                        }
                                    },
                                    "Jakarta Pusat": {
                                        "description": "Example updated office at Jakarta Pusat",
                                        "value": {
                                            "name": "Kedasi",
                                            "description": "Working space based in Jakarta Pusat",
                                            "tags": [
                                                "Jakarta Pusat"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": ["Office"],
                "summary": "Delete existing office",
                "description": "Delete existing office in database",
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "required": true,
                        "description": "Office id for updated",
                        "schema": {
                          "type": "string",
                          "nullable": true,
                          "minLength": 1,
                          "maxLength": 100
                        },
                        "examples": {
                          "Jakarta Utara": {
                            "description": "Working space at Jakarta Utara",
                            "value": "Jakarta Utara"
                          },
                          "Jakarta Pusat": {
                            "description": "Working space at Jakarta Pusat",
                            "value": "Jakarta Pusat"
                          }
                        }
                      }
                ],
                "responses": {
                    "200": {
                        "description": "Success delete office",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "success": {
                                        "description": "Success delete office",
                                        "value": {
                                            "success": true
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Failed delete not found todolist",
                        "content": {
                          "application/json": {
                            "schema": {
                              "type": "object",
                              "properties": {
                                "success": {
                                  "type": "boolean"
                                }
                              }
                            },
                            "examples": {
                              "failed": {
                                "description": "Failed delete todolist",
                                "value": {
                                  "success": false
                                }
                              }
                            }
                          }
                        }
                      }
                }
            }
        },
        "/transaction": {
            "get": {
                "tags": ["Transaction"],
                "summary": "Get all transaction",
                "description": "Get all transaction by default",
                
                  "responses": {
                    "200": {
                        "description" : "Success get all office",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type" : "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "description": {
                                            "type": "string"
                                        },
                                        "tags": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                                
                            }
                        }
                    }
                  }
            },
            "post" : {
                "tags": ["Transaction"]
            }
        },
        "/transaction/{transactionId}": {
            "put": {
                "tags": ["Transaction"]
            },
            "delete": {
                "tags": ["Transaction"]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "adminBearerAuth":{
                "description": "Authentication for Admin",
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            },
            "userBearerAuth":{
                "description": "Authentication for User",
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        },
        "parameters": {
            "AdminId": {
                "name": "adminId",
                "in": "path",
                "required": true,
                "description": "adminId for get admin by id, update",
                "schema": {
                    "type": "integer",
                    "minLength": 1,
                    "maxLength": 100
                },
                "examples": {
                    "admin1": {
                        "description": "Sample admin id for admin1",
                        "value": "1"
                    },
                    "admin2": {
                        "description": "Sample admin id for admin2",
                        "value": "2"
                    }
                }
            }
        },
        "schemas": {
            "Admins": {
                "type": "object",
                "properties": {
                    "username": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            },
            "ArrayAdmins": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/Admins"
                }
            },
            "BearerToken": {
                "type": "object",
                "properties": {
                    "token": {
                        "type": "string"
                    }
                }
            }
        }
    }
}